// ============================================================
// coach-rules.js — texto de las reglas para la vista Coach
// ============================================================
//
// GENERADO — no editar. Lo escribe scripts/build-rules-compact.mjs desde
// research/evidence-to-rules.md (fuente de verdad). Para regenerarlo:
//
//   node scripts/build-rules-compact.mjs
//
// sourceSha256: adc191dd05c53ba173cadc679f89b9f21674da2be67031a8693f2d5ce3ff2215
// count: 72
//
// POR QUÉ EXISTE. La vista Coach escribe "Rule STR-001 (strong evidence): <texto>" debajo de
// cada decisión del coach. Los Rule ID crudos en pantalla son ruido (§B.9) y el texto no puede
// venir por fetch: la app entrena sin conexión, así que el corpus va en el APP_SHELL. Sólo
// viajan `rule`, `evidenceLevel` y la PRIMERA salvedad (`caveat`): el resto de campos son
// para el prompt, no para la pantalla. La salvedad va porque una regla `strong` cuyo "pero" no
// se ve es media regla, y en la tarjeta cabe una linea, no las cinco de `caveats`.
// El texto de la regla se queda en el idioma del corpus (inglés) y la etiqueta de evidencia
// sale de COACH_EVIDENCE_LABEL en app/coach.js.

const COACH_RULES = {
  "GEN-001": { rule: "Prefer ONE dominant quality per block when weekly hard-stress is already at cap; two qualities may progress together at moderate loads. This is a fatigue-budgeting heuristic, not an interference finding.", evidenceLevel: "expert", caveat: "REATTRIBUTED 2026-08-16 (audit). Previously cited Huiberts 2024 + Soligard 2016 and graded moderate/high; NEITHER supports it. Huiberts 2024 finds interference…" },
  "GEN-002": { rule: "Do not apply beginner, obese, or elite-athlete evidence to this user without explicitly flagging it as extrapolated.", evidenceLevel: "strong", caveat: "Most dose-response curves are derived outside a deficit and in mixed populations." },
  "GEN-003": { rule: "When sources conflict, resolve by evidence grade x population fit; ties break toward lower fatigue/injury cost; log the conflict and decision.", evidenceLevel: "expert", caveat: "Expert opinion only breaks ties when primary evidence is silent." },
  "STR-001": { rule: "In a deficit, maintain load/intensity and cut volume first; do not chase net hypertrophy.", evidenceLevel: "strong", caveat: "Strength is preserved across a wide deficit; hypertrophy is the casualty." },
  "STR-002": { rule: "Train each muscle group / movement pattern 2x per week.", evidenceLevel: "strong", caveat: "Frequency is mainly a tool to distribute weekly volume, not an independent driver." },
  "STR-003": { rule: "Weekly volume 10-20 sets/muscle outside a deficit; cap at 10-14 sets/muscle during a deficit.", evidenceLevel: "strong", caveat: "Recovery ceiling is lower in a deficit, so 'more is more' inverts; the cap is recovery-driven, not an absolute hypertrophy ceiling." },
  "STR-004": { rule: "Default proximity to failure 1-3 RIR; reserve 0-1 RIR for isolation/machine work; never to failure on compounds in a deficit.", evidenceLevel: "moderate", caveat: "Hypertrophy improves modestly closer to failure; strength is largely RIR-insensitive (CIs include null). The marginal benefit doesn't justify recovery cost in …" },
  "STR-005": { rule: "Include at least one heavy slot (3-6 reps) per main movement pattern.", evidenceLevel: "strong", caveat: "Heavy strength is the anchor that preserves strength while dieting." },
  "STR-006": { rule: "Rest at least 2 min on compounds (2-3 min), 1-2 min on accessories.", evidenceLevel: "strong", caveat: "Load-bearing source is the Schoenfeld 2016 RCT (>=2-3 min > 1 min for strength AND hypertrophy in trained men). Grgic 2017 review is hypertrophy-only and equiv…" },
  "STR-007": { rule: "Use full ROM and emphasize lengthened (long muscle length) positions where joint-safe.", evidenceLevel: "strong", caveat: "Promising but young literature; do not sacrifice joint safety for length." },
  "STR-008": { rule: "Periodization model is hypertrophy-insensitive when volume/intensity are equated; for strength, undulating is modestly superior to linear in trained lifters, and any periodization beats none. Periodize for strength, variety and adherence, not for a hypertrophy advantage.", evidenceLevel: "moderate", caveat: "Moesgaard: hypertrophy LP=UP when equated, but UP modestly beats LP for strength in TRAINED subgroups. Williams compares periodized vs non-periodized (favors p…" },
  "STR-009": { rule: "Progress by DOUBLE PROGRESSION: hold the load until the top of the prescribed rep window is reached on every working set at or below the target RPE, then add the smallest available increment and drop back to the bottom of the window. Reps first, load second, sets last.", evidenceLevel: "expert", caveat: "EXPERT, not moderate: no double-progression RCT is in corpus-map.md (Plotkin 2022 is NOT in the corpus), so the METHOD is applied practice. What is evidence-ba…" },
  "STR-010": { rule: "Keep main compounds stable for progression; rotate accessories at block boundaries (4-6 wk) with purpose, not weekly.", evidenceLevel: "expert", caveat: "Weekly random rotation destroys progression tracking." },
  "REC-001": { rule: "Protein 1.6-2.2 g/kg bodyweight (ACSM says 1.2-2.0; extrapolated upward inside a deficit per Helms/ISSN); bias higher when leaner or in a larger deficit.", evidenceLevel: "strong", caveat: "RANGE REWRITTEN 2026-09-08 (app audit R-6). The old declared range (1.8-2.7 g/kg) had no source behind its upper half: ACSM 2016 (acsm-summaries.md S3:138-141)…" },
  "REC-002": { rule: "Rate of loss is a dial of 0.5-1.0% bodyweight/week, governed by performance and wellness; go slower the leaner/more trained.", evidenceLevel: "strong", caveat: "Murphy & Koehler 2022 supports: deficit impairs lean-mass gain (not strength) and scales with deficit severity (~500 kcal/day threshold). It does NOT support '…" },
  "REC-003": { rule: "Recomposition magnitude decreases with training age and leanness; set realistic expectations (slow simultaneous gain/loss in trained adults).", evidenceLevel: "expert", caveat: "'Fast fat loss + muscle gain' is mostly a beginner/returning/high-bodyfat phenomenon." },
  "REC-004": { rule: "Exploit the return-from-layoff window: muscle-memory favors recomposition for the first weeks back.", evidenceLevel: "moderate", caveat: "User is in a re-entry block after a ~6-week layoff; window is temporary." },
  "REC-005": { rule: "Schedule maintenance diet breaks aligned with training deloads to improve fat-loss efficiency and blunt metabolic adaptation (NOT to preserve more lean mass).", evidenceLevel: "weak_extrapolated", caveat: "Existing system already runs diet breaks on weeks 5 & 9." },
  "REC-006": { rule: "Drink 5-10 mL/kg bodyweight of fluid in the 2-4 h before a session (~500 mL for this user); keep within-session losses under 2% bodyweight.", evidenceLevel: "strong", caveat: "Already practised in plans/nutrition-notes.md since W19; formalised as a Rule ID 2026-08-16 so the engine can act on it." },
  "REC-007": { rule: "Periodise carbohydrate by day type rather than raising total intake: more on heavy-lower and long-cardio days, less on rest days, protein and weekly calories unchanged.", evidenceLevel: "moderate", caveat: "The user's baseline (~3.2 g/kg) sits BELOW the ACSM moderate band by deliberate choice - carbohydrate absorbs the deficit. Redistribution is the lever availabl…" },
  "REC-008": { rule: "Keep energy availability above ~30 kcal/kg FFM/day; treat sustained low EA as an upstream gate on training load, confirmed by symptoms rather than by the arithmetic alone.", evidenceLevel: "moderate", caveat: "The 30 kcal/kg FFM/d threshold comes largely from female athlete/RED-S literature; applicability to a male recreational lifter is an extrapolation of DIRECTION…" },
  "REC-009": { rule: "Hold a daily step floor (~7,000-10,000) through the deficit; NEAT falls spontaneously as energy intake drops.", evidenceLevel: "moderate", caveat: "Steps are ALREADY ingested (store `steps`, via the intervals.icu companion) - this is the cheapest unused signal in the system." },
  "INT-001": { rule: "Avoid hard running within 24h before heavy lower-body strength sessions.", evidenceLevel: "moderate", caveat: "Depends on running intensity and weekly volume; bike/row/ski may substitute when lower-limb fatigue is high." },
  "INT-002": { rule: "Running produces more lower-limb interference and impact than cycling/rowing/ski; prefer low-interference modality when legs are fatigued or impact must be limited.", evidenceLevel: "strong", caveat: "Running specificity is still required to build running capacity (see END-007/SEL-004 trade-off)." },
  "INT-003": { rule: "If strength and endurance share a session, lift first when strength is the priority.", evidenceLevel: "weak_extrapolated", caveat: "Reverse if the day's dominant goal is aerobic." },
  "INT-004": { rule: "Protect power/explosive work: place it fresh, early, never after endurance or under accumulated fatigue.", evidenceLevel: "strong" },
  "INT-005": { rule: "Reject the claim that cardio inherently kills strength/hypertrophy; moderate cardio does not meaningfully blunt gains if volume is managed and not placed immediately pre-lift.", evidenceLevel: "strong", caveat: "Interference is dose-dependent; high-volume/high-frequency endurance still matters." },
  "INT-006": { rule: "Cap total endurance volume during strength-priority blocks.", evidenceLevel: "moderate", caveat: "Wilson 2012 supports volume-dependence (verified). Fyfe 2014 NAMES the levers (intensity/volume/modality) but explicitly does NOT prove that managing them redu…" },
  "END-001": { rule: "Keep roughly 80/20 easy/hard intensity distribution across the WHOLE week, not just running.", evidenceLevel: "strong", caveat: "TID literature is from competitive endurance athletes; for 2-3 runs/wk it simplifies to 'mostly easy + occasional quality'." },
  "END-002": { rule: "Anchor running zones to HR/RPE early; introduce pace targets later. Daniels VDOT paces are too fast for a 5k-novice.", evidenceLevel: "moderate", caveat: "Daniels is a session toolbox here, not an authority." },
  "END-003": { rule: "Progress running volume by ~10%/week soft cap with periodic down weeks.", evidenceLevel: "moderate", caveat: "Bertelsen 2017 (verified) supports the load-vs-capacity MECHANISM (injury when load exceeds tissue capacity); the 'gradual progression' prescription is a model…" },
  "END-004": { rule: "Intervals max 1 session/week, never colliding with heavy legs.", evidenceLevel: "moderate" },
  "END-005": { rule: "Measure Z2 aerobic improvement by aerobic decoupling (<5%) and pace-at-fixed-HR, not raw speed.", evidenceLevel: "expert", caveat: "The decoupling METRIC and <5% threshold are practitioner methodology (expert), NOT validated diagnostics; underlying cardiovascular-drift PHYSIOLOGY is real (m…" },
  "END-006": { rule: "Use run/walk intervals when aerobic base is low or HR drift is high.", evidenceLevel: "moderate" },
  "END-007": { rule: "Maintain heavy strength and low-dose plyometrics during running blocks; they improve running economy.", evidenceLevel: "strong" },
  "END-008": { rule: "HIIT and MICT both raise VO2max; choose by fatigue cost, time, and specificity rather than dogma.", evidenceLevel: "strong", caveat: "HIIT carries higher fatigue + interference cost; count it in the hard-day budget." },
  "END-009": { rule: "Hold at least 150 min/week of moderate-to-vigorous physical activity as the floor, and aim at 200-300 min/week while losing fat: the dose-response for weight loss runs across that band, and higher doses buy little extra once the loss is being maintained.", evidenceLevel: "strong", caveat: "The 150 min floor and the 200-300 min band are POPULATION doses for body-weight regulation in adults with excess adiposity, not a performance prescription for …" },
  "HYB-001": { rule: "Hybrid/HYROX-like frequency: 0-1 session/week in a cut or strength block; up to 2 only in a dedicated work-capacity block.", evidenceLevel: "weak_extrapolated", caveat: "No direct HYROX programming RCTs; logic is principle-based." },
  "HYB-002": { rule: "Hybrid conditioning counts as a hard day and a partial leg/systemic stressor; space it from heavy legs and hard runs.", evidenceLevel: "weak_extrapolated", caveat: "Deceptively fatiguing; competes with both legs and runs for recovery." },
  "HYB-003": { rule: "Under fatigue, use only low-skill movements in hybrid sessions (sled, carries, lunges, wall ball, ergs); no Olympic lifts or gymnastics.", evidenceLevel: "expert" },
  "HYB-004": { rule: "Hybrid benchmarks no more than once every 4-6 weeks; not a weekly session type.", evidenceLevel: "expert", caveat: "Benchmarks are the highest hard-day cost (BUD weight 3)." },
  "HYB-005": { rule: "Use indoor low-impact hybrid (row/ski/bike/sled) when impact or lower-limb load must be limited.", evidenceLevel: "moderate" },
  "ATH-001": { rule: "Plyometrics at low dose (~40-80 contacts/session), progress slowly, introduce after an aerobic/strength base.", evidenceLevel: "moderate", caveat: "Plyo improves jump/power and benefits trained subjects (verified). BUT 'low-dose is optimal' is NOT supported - the dose-response meta favors HIGHER volume (>2…" },
  "ATH-002": { rule: "Microdose power work fresh at session start, low volume, maximal intent.", evidenceLevel: "moderate", caveat: "TRADE-OFF (verified): low velocity-loss preserves STRENGTH + fast-fiber quality with less fatigue/volume; HIGHER velocity-loss drives MORE hypertrophy. So low-…" },
  "ATH-003": { rule: "Prioritize anti-rotation / anti-extension core work (Pallof, dead bug, carries, ab wheel).", evidenceLevel: "strong", caveat: "Especially relevant given the user's lumbar history." },
  "ATH-004": { rule: "Introduce plyometrics only after aerobic and strength base; tendons adapt slowly.", evidenceLevel: "moderate", caveat: "Tendons adapt slowly; sequence plyo after base." },
  "ATH-005": { rule: "Unilateral lower-body training transfers comparably to bilateral for strength and adds knee/hip resilience and athletic carryover.", evidenceLevel: "weak_extrapolated", caveat: "VERIFIED but scope-limited: n=18 YOUNG MALE RUGBY players, 5 wk, sprint/agility outcomes (not the user's goals). Failure to detect a group difference in a smal…" },
  "ATH-006": { rule: "Hold a mobility/flexibility floor of 2-3 sessions per week, ~60 s total per major muscle-tendon unit.", evidenceLevel: "moderate", caveat: "Garber 2011 prescribes a flexibility dose but does NOT establish that it prevents injury - do not oversell it as prophylaxis." },
  "READ-001": { rule: "Use 7-day rolling trends for HRV/RHR, not isolated daily values.", evidenceLevel: "strong", caveat: "Whoop reports a proprietary HRV during sleep, NOT standardized morning RMSSD used in the literature - values/trends are not directly interchangeable. The valid…" },
  "READ-002": { rule: "Require multi-signal confirmation (>=2 concordant signals) before changing the plan.", evidenceLevel: "strong" },
  "READ-003": { rule: "Treat Whoop Recovery score as a yellow/red flag, never as an exact dose calculator.", evidenceLevel: "expert", caveat: "Composite score; do not derive set/rep numbers from it." },
  "READ-004": { rule: "Interpret HRV against the individual's own baseline; never compare across people.", evidenceLevel: "strong", caveat: "HRV-guided RCT evidence (Vesterinen 2016 n=40 recreational; Javaloyes 2019 n=17 cyclists; Granero-Gallegos 2020 meta) supports trend-based use, with benefit la…" },
  "READ-005": { rule: "When wearable scores conflict with actual performance and subjective state, prioritize performance + subjective feedback.", evidenceLevel: "strong" },
  "READ-006": { rule: "Treat sleep (duration + consistency) as the primary recovery lever.", evidenceLevel: "strong", caveat: "Fullagar is a NARRATIVE review and notes the evidence is partly equivocal; 'sleep matters for recovery/performance' is well-supported broadly, but this single …" },
  "READ-007": { rule: "A red day changes the session OBJECTIVE (downgrade/replace), not merely the load.", evidenceLevel: "expert" },
  "READ-008": { rule: "Trigger a deload on sustained multi-signal decline (HRV down + RHR up + performance down + wellness down).", evidenceLevel: "expert", caveat: "Consensus statement (expert by design). It explicitly warns AGAINST relying on any single marker - prolonged performance decline confirmed by testing is the an…" },
  "LOAD-001": { rule: "Avoid abrupt load spikes and build chronic capacity as a PRINCIPLE; do not apply rigid ACWR thresholds.", evidenceLevel: "strong", caveat: "The 'no rigid ACWR thresholds' part is strongly supported (Impellizzeri 2020, verified). The 'spikes drive injury' part is weaker - Nielsen 2012 was inconclusi…" },
  "LOAD-002": { rule: "For tendon issues, load progressively (isometrics/heavy-slow resistance); do not rest to zero.", evidenceLevel: "strong", caveat: "Complete rest deconditions tendons (Cook & Purdam). HSR/progressive loading well-supported (Malliaras 2013). Isometric analgesia: Rio 2015 verified but n=6 acu…" },
  "LOAD-003": { rule: "On low-back pain, modify variant/ROM/load; do not reflexively remove strength training.", evidenceLevel: "moderate", caveat: "User has lumbar history; sumo DL already RPE-gated." },
  "LOAD-004": { rule: "Deload every 4-6 weeks, or reactively after two consecutive sessions of performance decline.", evidenceLevel: "expert", caveat: "DOWNGRADED to expert 2026-09-08 (app audit R-3). There is no trial behind '4-6 weeks' or behind the reactive trigger; both are applied practice written into tr…" },
  "SEL-001": { rule: "Machines and free weights produce similar hypertrophy/strength when matched; choose by ROI, stability, joint comfort, and fatigue.", evidenceLevel: "strong", caveat: "Verified: machine vs free = no hypertrophy/strength/jump difference; the ONLY reliable difference is test-specificity (you get better at what you train). So tr…" },
  "SEL-002": { rule: "Select exercises by stimulus-to-fatigue ratio and joint-stress profile, not novelty or variety for its own sake.", evidenceLevel: "expert", caveat: "SFR is a qualitative heuristic, not a measured number (see exercise-schema-v1)." },
  "SEL-003": { rule: "Do not use EMG amplitude as a direct proxy for hypertrophy; ignore EMG-based exercise hype.", evidenceLevel: "weak_extrapolated", caveat: "This rule REFUTES a common claim." },
  "SEL-004": { rule: "Select cardio modality by impact + interference + recent lower-limb load + goal specificity.", evidenceLevel: "strong", caveat: "Running specificity vs interference is the core trade-off; see cardio-modality-schema-v1." },
  "BUD-001": { rule: "No more than 2-3 truly hard sessions per week counting ALL modalities (heavy strength, intervals, threshold, hard hybrid, demanding long run).", evidenceLevel: "moderate", caveat: "The 80/20 distribution applies to the entire training week, not just running." },
  "BUD-002": { rule: "Assign each session a hard-stress weight and keep the weekly sum under the block's budget cap.", evidenceLevel: "expert", caveat: "Weights are heuristic starting points, refined with logged data; not falsely precise." },
  "LONG-001": { rule: "Treat cardiorespiratory fitness as a health outcome in its own right, not only as a means to body composition: the fitness-mortality gradient is steep and shows no upper limit of benefit.", evidenceLevel: "strong", caveat: "OBSERVATIONAL. A dose-response association, not a randomised demonstration that raising CRF lowers mortality; reverse causation and residual confounding are li…" },
  "LONG-002": { rule: "Keep resistance training in the plan for health reasons independent of hypertrophy or aesthetics; ~30-60 min/week of muscle-strengthening activity carries most of the mortality benefit.", evidenceLevel: "strong", caveat: "OBSERVATIONAL, both. Grip strength is a MARKER of overall health, not a target to train - do not infer that grip work lowers mortality." },
  "LONG-003": { rule: "Track health markers longitudinally and surface them as context; never derive treatment from them. Abnormal markers are a referral, not a programming input.", evidenceLevel: "expert", caveat: "This is a GUARDRAIL, not a finding. A training system must not titrate lipids, prescribe supplements against a deficiency, or interpret an abnormal panel." },
  "LONG-004": { rule: "Protect habitual sleep duration in the 7-8 h range as a longevity target, not only a recovery lever; both short and long sleep associate with higher mortality.", evidenceLevel: "moderate", caveat: "OBSERVATIONAL and U-shaped: the long-sleep limb is widely read as reverse causation (illness causes long sleep), so do NOT treat a long night as a risk signal." },
  "ENV-001": { rule: "In the heat, hold the HR target and let pace fall; do not chase the usual pace. For the same power output, heart rate rises with heat strain, so an HR-anchored easy run is simply slower in August.", evidenceLevel: "moderate", caveat: "The PHYSIOLOGY is well established (HR up and stroke volume down for a given work rate in heat, partially reversing over ~1-2 weeks of acclimation). The PRESCR…" },
  "ENV-002": { rule: "Move hard or long sessions indoors, or to the cooler ends of the day, when heat is high; raise fluid intake above the REC-006 baseline and treat heat as a hard-day cost multiplier.", evidenceLevel: "moderate", caveat: "NEITHER PDF is in data/ACSM/ - cited from verified bibliographic records, so the specific thresholds are NOT quoted here. Marked as an acquisition item in corp…" },
};

if (typeof module !== 'undefined' && module.exports) module.exports = { COACH_RULES };
