-- Coach v2 (2026-09-07): dos tablas genéricas nuevas, mismo patrón que foods/meals/plans.
-- Aplicada en el proyecto ycfodifvpvosukepcxie vía MCP (migración "coach_reviews_and_decisions").
-- coach_reviews: una fila por revisión semanal del coach (facts pack, salida del modelo, propuesta, estado).
-- decisions: registro de decisiones (coach, regla, readiness, usuario) para el "te propuse X, hiciste Y".
-- Se crean ANTES de añadir los stores a la lista de sync de la PWA (regla de db-schema-state.md).

create table if not exists public.coach_reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  record_id text not null,
  data jsonb not null,
  updated_at timestamptz default now(),
  unique (user_id, record_id)
);
alter table public.coach_reviews enable row level security;
create policy "Users see own coach_reviews" on public.coach_reviews
  for all using (auth.uid() = user_id);
create index if not exists coach_reviews_user_updated_idx on public.coach_reviews (user_id, updated_at);

create table if not exists public.decisions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  record_id text not null,
  data jsonb not null,
  updated_at timestamptz default now(),
  unique (user_id, record_id)
);
alter table public.decisions enable row level security;
create policy "Users see own decisions" on public.decisions
  for all using (auth.uid() = user_id);
create index if not exists decisions_user_updated_idx on public.decisions (user_id, updated_at);
